// Generated by CoffeeScript 1.9.0
var americano;

americano = require('americano-cozy');

module.exports = {
  name: "Bank Operations",
  color: "#297FC8",
  description: "Sum of every bank operations (all accounts).",
  model: americano.getModel('bankoperation', {
    date: Date
  }),
  requestName: 'allOpsByDay',
  request: {
    map: function(doc) {
      return emit(doc.date.substring(0, 10), doc.amount);
    },
    reduce: function(key, values, rereduce) {
      return sum(values);
    }
  }
};
