// Generated by CoffeeScript 1.7.1
var americano;

americano = require('americano-cozy');

module.exports = {
  name: "Bank Operations",
  color: "#297FC8",
  description: "Sum of every bank operations (all accounts).",
  model: americano.getModel('bankoperation', {
    date: Date
  }),
  request: {
    map: function(doc) {
      var sign;
      sign = 1;
      if (doc.amount < 0) {
        sign = -1;
      }
      return emit(doc.date.substring(0, 10), sign * doc.amount);
    },
    reduce: function(key, values, rereduce) {
      return sum(values);
    }
  }
};
