// Generated by CoffeeScript 1.7.1
var americano;

americano = require('americano-cozy');

module.exports = {
  name: "Commits",
  color: "#408000",
  description: "This tracker counts your amount of commits on a daily basis.",
  model: americano.getModel('Commit', {
    date: Date
  }),
  request: {
    map: function(doc) {
      return emit(doc.date.substring(0, 10), 1);
    },
    reduce: function(key, values, rereduce) {
      return sum(values);
    }
  }
};
