// Generated by CoffeeScript 1.10.0
var americano;

americano = require('cozydb');

module.exports = {
  name: "Emails",
  color: "#00BCD4",
  description: "Number of emails stored in your Cozy.",
  model: americano.getModel('message', {
    date: Date
  }),
  request: {
    map: function(doc) {
      return emit(doc.date.substring(0, 10), 1);
    },
    reduce: function(key, values, rereduce) {
      return sum(values);
    }
  }
};
