// Generated by CoffeeScript 1.9.3
var americano;

americano = require('americano-cozy');

module.exports = {
  name: "Events",
  color: "#9B58B5",
  description: "Number of emails stored in your Cozy for each day.",
  model: americano.getModel('Event', {
    date: Date
  }),
  request: {
    map: function(doc) {
      var date, dateString, dd, mm, yyyy;
      if (doc.start) {
        date = new Date(doc.start);
        yyyy = date.getFullYear().toString();
        mm = (date.getMonth() + 1).toString();
        if (mm.length === 1) {
          mm = "0" + mm;
        }
        dd = date.getDate().toString();
        if (dd.length === 1) {
          dd = "0" + dd;
        }
        dateString = yyyy + '-' + mm + '-' + dd;
        return emit(dateString, 1);
      }
    },
    reduce: function(key, values, rereduce) {
      return sum(values);
    }
  }
};
