// Generated by CoffeeScript 1.10.0
var americano;

americano = require('cozydb');

module.exports = {
  name: "Productive Time",
  color: "#2196F3",
  description: "Number of minutes spent on apps and websites with productivity rating superior to\n0 in Rescue Time. Data should be imported from Rescue Time konnector",
  model: americano.getModel('RescueTimeActivity', {
    date: Date
  }),
  request: {
    map: function(doc) {
      if (doc.productivity > 0) {
        return emit(doc.date.substring(0, 10), doc.duration / 60);
      }
    },
    reduce: function(key, values, rereduce) {
      return sum(values);
    }
  }
};
