// Generated by CoffeeScript 1.9.3
var americano;

americano = require('cozydb');

module.exports = {
  name: "Sleep Duration",
  color: "#2196F3",
  description: "Number of minutes you sleep every day. Data should be imported from Jawbone\nKonnector.",
  model: americano.getModel('sleep', {
    date: Date
  }),
  request: {
    map: function(doc) {
      return emit(doc.date.substring(0, 10), doc.sleepDuration / 60);
    },
    reduce: function(key, values, rereduce) {
      return sum(values);
    }
  }
};
