// Generated by CoffeeScript 1.9.3
var americano;

americano = require('cozydb');

module.exports = {
  name: "Steps",
  color: "#795548",
  description: "Number of steps you walked.",
  model: americano.getModel('steps', {
    date: Date
  }),
  request: {
    map: function(doc) {
      return emit(doc.date.substring(0, 10), doc.steps);
    },
    reduce: function(key, values, rereduce) {
      return sum(values);
    }
  }
};
