// Generated by CoffeeScript 1.9.3
var americano;

americano = require('cozydb');

module.exports = {
  name: "Tweets",
  color: "#E91E63",
  description: "Number of tweets you publish every day",
  model: americano.getModel('twittertweet', {
    date: Date
  }),
  request: {
    map: function(doc) {
      return emit(doc.date.substring(0, 10), 1);
    },
    reduce: function(key, values, rereduce) {
      return sum(values);
    }
  }
};
