ViewCollection = require 'lib/view_collection'
BasicTrackerCollection = require 'collections/basic_trackers'


# View to display a tracker where data are from generated by other Cozy apps
# like email.
module.exports = class AddBasicTrackerList extends ViewCollection
    el: '#add-basic-tracker-list'
    collectionEl: '#add-basic-tracker-list'
    itemView: require 'views/add_basic_tracker_list_item'
    template: require 'views/templates/add_basic_tracker_list'


    constructor: (@collection) ->
        super
        @$collectionEl = $ @collectionEl


    afterRender: ->
        super

