// Generated by CoffeeScript 1.6.3
var CoffeeCup, americano, moment;

americano = require('americano-cozy');

moment = require('moment');

module.exports = CoffeeCup = americano.getModel('CoffeeCup', {
  date: Date,
  amount: Number
});

CoffeeCup.getConsumption = function(day, callback) {
  day = moment(day).format('YYYY-MM-DD');
  return CoffeeCup.request('byDay', {
    key: day
  }, function(err, coffeeCups) {
    if (err) {
      return callback(err);
    } else if (moods.length !== 0) {
      return callback(null, moods[0]);
    } else {
      return callback();
    }
  });
};
