// Generated by CoffeeScript 1.6.3
var CoffeeCup, americano, date_helpers;

americano = require('americano-cozy');

date_helpers = require('../lib/date');

module.exports = CoffeeCup = americano.getModel('CoffeeCup', {
  date: Date,
  amount: Number
});

CoffeeCup.loadTodayConsumption = function(callback) {
  return CoffeeCup.request('byDay', {
    descending: true
  }, function(err, coffeeCups) {
    return date_helpers.getTodayModel(err, coffeeCups, callback);
  });
};
