// Generated by CoffeeScript 1.10.0
var DailyNote, americano, moment;

americano = require('cozydb');

moment = require('moment');

module.exports = DailyNote = americano.getModel('DailyNote', {
  text: String,
  date: Date
});

DailyNote.getDailyNote = function(day, callback) {
  day = day.format('YYYY-MM-DD');
  return DailyNote.request('byDay', {
    key: day
  }, function(err, dailynotes) {
    if (err) {
      return callback(err);
    } else if (dailynotes.length !== 0) {
      return callback(null, dailynotes[0]);
    } else {
      return callback();
    }
  });
};
