// Generated by CoffeeScript 1.6.3
var americano;

americano = require('americano-cozy');

module.exports = {
  mail: {
    nbByDay: {
      map: function(doc) {
        if (doc.date != null) {
          return emit(doc.date.substring(0, 10), 1);
        }
      },
      reduce: function(key, values, rereduce) {
        return sum(values);
      }
    }
  },
  task: {
    nbByDay: {
      map: function(doc) {
        var date, dateString, dd, mm, yyyy;
        if ((doc.completionDate != null) && doc.done) {
          date = new Date(doc.completionDate);
          yyyy = date.getFullYear().toString();
          mm = (date.getMonth() + 1).toString();
          if (mm.length === 1) {
            mm = "0" + mm;
          }
          dd = date.getDate().toString();
          if (dd.length === 1) {
            dd = "0" + dd;
          }
          dateString = yyyy + '-' + mm + '-' + dd;
          return emit(dateString, 1);
        }
      },
      reduce: function(key, values, rereduce) {
        return sum(values);
      }
    }
  },
  mood: {
    all: americano.defaultRequests.all,
    statusByDay: function(doc) {
      var status;
      status = 0;
      if (doc.status === "bad") {
        status = 1;
      }
      if (doc.status === "neutral") {
        status = 2;
      }
      if (doc.status === "good") {
        status = 3;
      }
      return emit(doc.date.substring(0, 10), status);
    },
    byDay: function(doc) {
      return emit(doc.date.substring(0, 10), doc);
    }
  },
  coffeecup: {
    nbByDay: function(doc) {
      return emit(doc.date.substring(0, 10), doc.amount);
    },
    byDay: function(doc) {
      return emit(doc.date, doc);
    }
  },
  tracker: {
    all: americano.defaultRequests.all
  },
  trackeramount: {
    nbByDay: function(doc) {
      return emit([doc.tracker, doc.date.substring(0, 10)], doc.amount);
    },
    byDay: function(doc) {
      return emit([doc.tracker, doc.date], doc);
    }
  }
};
