// Generated by CoffeeScript 1.6.3
var Tracker, TrackerAmount, americano, date_helpers;

americano = require('americano-cozy');

date_helpers = require('../lib/date');

TrackerAmount = require('./trackeramount');

module.exports = Tracker = americano.getModel('Tracker', {
  name: String,
  description: String,
  amount: Number
});

Tracker.prototype.loadTodayAmount = function(callback) {
  var params;
  console.log(this.id);
  params = {
    startkey: [this.id],
    endkey: [this.id + "0"],
    descending: false
  };
  return TrackerAmount.request('byDay', params, function(err, trackerAmounts) {
    console.log(trackerAmounts);
    return date_helpers.getTodayModel(err, trackerAmounts, callback);
  });
};
