// Generated by CoffeeScript 1.10.0
var Mood, moment, normalizer;

Mood = require('../models/mood');

moment = require('moment');

normalizer = require('../lib/normalizer');

module.exports = {
  all: function(req, res, next) {
    var endDate, options, startDate;
    endDate = req.params.endDate;
    startDate = req.params.startDate;
    if (endDate == null) {
      endDate = moment().format('YYYY-MM-DD');
    }
    if (startDate == null) {
      startDate = moment(req.endDate, 'YYYY-MM-DD').subtract('month', 6).format('YYYY-MM-DD');
    }
    options = {
      startkey: startDate,
      endkey: endDate
    };
    return Mood.rawRequest('statusByDay', options, function(err, rows) {
      var data;
      if (err) {
        return next(err);
      } else {
        data = normalizer.normalize(rows, startDate, endDate);
        return res.send(normalizer.toClientFormat(data));
      }
    });
  },
  day: function(req, res, next) {
    return Mood.getMood(req.day, function(err, mood) {
      if (err) {
        return next(err);
      } else if (mood != null) {
        return res.send(mood);
      } else {
        return res.send({});
      }
    });
  },
  updateDay: function(req, res, next) {
    return Mood.getMood(req.day, function(err, mood) {
      var data;
      if (err) {
        return next(err);
      } else if (mood != null) {
        mood.status = req.body.status;
        return mood.save(function(err) {
          if (err) {
            return next(err);
          } else {
            return res.send(mood);
          }
        });
      } else {
        data = {
          status: req.body.status,
          date: req.day
        };
        return Mood.create(data, function(err, mood) {
          if (err) {
            return next(err);
          } else {
            return res.send(mood);
          }
        });
      }
    });
  },
  "export": function(req, res, next) {
    var slug;
    slug = req.params.slug;
    return Mood.all(function(err, rows) {
      var csv, csvFile, i, key, len, row, value;
      if (err) {
        return next(err);
      }
      csv = [];
      for (i = 0, len = rows.length; i < len; i++) {
        row = rows[i];
        key = moment(row.date).format('YYYY-MM-DD');
        value = row.status;
        csv.push(key + "," + value);
      }
      csvFile = csv.join('\n');
      res.setHeader('Content-length', csvFile.length);
      res.setHeader('Content-disposition', "attachment; filename=mood.csv");
      res.setHeader('Content-type', 'application/csv');
      return res.send(csvFile);
    });
  }
};
