// Generated by CoffeeScript 1.6.3
var Task, moment, normalizeResults;

Task = require('../models/task');

normalizeResults = require('../lib/normalizer');

moment = require('moment');

module.exports.all = function(req, res, next) {
  var options;
  options = {
    group: true
  };
  return Task.rawRequest('nbByDay', options, function(err, rows) {
    var data, date, dateEpoch, limitDate, results, value;
    if (err) {
      return next(err);
    } else {
      results = [];
      limitDate = moment(req.params.day);
      data = normalizeResults(rows, limitDate);
      for (date in data) {
        value = data[date];
        dateEpoch = new Date(date).getTime() / 1000;
        results.push({
          x: dateEpoch,
          y: value
        });
      }
      return res.send(results);
    }
  });
};
