// Generated by CoffeeScript 1.6.3
var fs, getTrackers, log, moment, normalizeResults, path, slugify;

fs = require('fs');

path = require('path');

moment = require('moment');

slugify = require('cozy-slug');

log = require('printit')({
  prefix: 'init tracker',
  date: true
});

normalizeResults = require('../lib/normalizer');

getTrackers = require('../lib/trackers').getTrackers;

module.exports = function(app) {
  var getController, recConfig, trackers;
  getController = function(tracker) {
    return function(req, res, next) {
      var options;
      options = {
        group: true
      };
      return tracker.model.rawRequest('nbByDay', options, function(err, rows) {
        var data, date, dateEpoch, limitDate, results, value;
        if (err) {
          return next(err);
        } else {
          results = [];
          limitDate = moment(req.params.day);
          data = normalizeResults(rows, limitDate);
          for (date in data) {
            value = data[date];
            dateEpoch = new Date(date).getTime() / 1000;
            results.push({
              x: dateEpoch,
              y: value
            });
          }
          return res.send(results);
        }
      });
    };
  };
  recConfig = function() {
    var slug, tracker;
    if (trackers.length > 0) {
      tracker = trackers.pop();
      log.info("configure tracker " + tracker.name);
      slug = slugify(tracker.name);
      path = "/basic-trackers/" + slug;
      app.get(path, getController(tracker));
      log.info('Tracker controller added.');
      return tracker.model.defineRequest('nbByDay', tracker.request, function(err) {
        if (err) {
          log.error('Tracker request creation failed.');
          return recConfig();
        } else {
          log.info('Tracker request creation succeed.');
          return recConfig();
        }
      });
    }
  };
  trackers = getTrackers().reverse();
  return recConfig();
};
