// Generated by CoffeeScript 1.9.3
var fs, log, moment, normalizer, path, trackers;

fs = require('fs');

path = require('path');

moment = require('moment');

log = require('printit')({
  prefix: 'init tracker',
  date: true
});

normalizer = require('../lib/normalizer');

trackers = require('../lib/trackers')();

module.exports = function(app) {
  var getController, recConfig;
  getController = function(tracker) {
    return function(req, res, next) {
      var endDate, options, startDate;
      endDate = req.params.endDate;
      startDate = req.params.startDate;
      if (endDate == null) {
        endDate = moment().format('YYYY-MM-DD');
      }
      if (startDate == null) {
        startDate = moment(req.endDate, 'YYYY-MM-DD').subtract('month', 6).format('YYYY-MM-DD');
      }
      options = {
        group: true
      };
      options.startkey = startDate;
      options.endkey = endDate;
      return tracker.model.rawRequest(tracker.requestName, options, function(err, rows) {
        var data;
        if (err) {
          return next(err);
        } else {
          data = normalizer.normalize(rows, startDate, endDate);
          return res.send(normalizer.toClientFormat(data));
        }
      });
    };
  };
  recConfig = function(trackers) {
    var name, slug, tracker;
    if (trackers.length > 0) {
      tracker = trackers.pop();
      log.info("configure tracker " + tracker.name);
      slug = tracker.slug;
      path = "/basic-trackers/" + slug;
      if (tracker.requestName == null) {
        tracker.requestName = 'nbByDay';
      }
      app.get(path + "/:startDate/:endDate", getController(tracker));
      log.info('Tracker controller added.');
      name = tracker.requestName;
      return tracker.model.defineRequest(name, tracker.request, function(err) {
        if (err) {
          log.error('Tracker request creation failed.');
          return recConfig();
        } else {
          log.info('Tracker request creation succeeded.');
          return recConfig(trackers);
        }
      });
    }
  };
  return recConfig(trackers.reverse());
};
