// Generated by CoffeeScript 1.9.0
var getDateString;

module.exports.getDateString = getDateString = function(date) {
  var dateString, dd, mm, yyyy;
  yyyy = date.getFullYear().toString();
  mm = (date.getMonth() + 1).toString();
  if (mm.length === 1) {
    mm = "0" + mm;
  }
  dd = date.getDate().toString();
  if (dd.length === 1) {
    dd = "0" + dd;
  }
  dateString = yyyy + '-' + mm + '-' + dd;
  return dateString;
};
