// Generated by CoffeeScript 1.9.3
var moment;

moment = require('moment');

module.exports = {
  normalize: function(rows, start, end) {
    var data, i, len, row;
    data = {};
    data[start] = 0;
    for (i = 0, len = rows.length; i < len; i++) {
      row = rows[i];
      data[row.key] = row.value;
    }
    if (data[end] == null) {
      data[end] = 0;
    }
    return data;
  },
  toClientFormat: function(data) {
    var date, dateEpoch, results, value;
    results = [];
    for (date in data) {
      value = data[date];
      dateEpoch = new Date(date).getTime() / 1000;
      results.push({
        x: dateEpoch,
        y: value
      });
    }
    return results;
  }
};
