// Generated by CoffeeScript 1.9.0
var fs, isJsFile, path;

path = require('path');

fs = require('fs');

isJsFile = function(fileName) {
  var extension, firstChar;
  extension = fileName.split('.')[1];
  firstChar = fileName[0];
  return firstChar !== '.' && extension === 'js';
};

module.exports = {
  getTrackers: function() {
    var currentPath, modulePath, modulesPath, name, trackerFile, trackerFiles, trackers, _i, _len;
    currentPath = path.dirname(fs.realpathSync(__filename));
    modulesPath = path.join(currentPath, '..', 'trackers');
    trackers = [];
    trackerFiles = fs.readdirSync(modulesPath);
    for (_i = 0, _len = trackerFiles.length; _i < _len; _i++) {
      trackerFile = trackerFiles[_i];
      if (isJsFile(trackerFile)) {
        name = trackerFile.split('.')[0];
        modulePath = path.join(modulesPath, name);
        trackers.push(require(modulePath));
      }
    }
    trackers.sort(function(a, b) {
      var nameA, nameB;
      nameA = a.name.toLowerCase();
      nameB = b.name.toLowerCase();
      if (nameA < nameB) {
        return -1;
      } else if (nameA > nameB) {
        return 1;
      } else {
        return 0;
      }
    });
    return trackers;
  }
};
