// Generated by CoffeeScript 1.9.3
var _, basicTrackers, cloneTrackers, fs, getTrackers, isJsFile, path, slugify;

path = require('path');

fs = require('fs');

slugify = require('cozy-slug');

_ = require('underscore');

isJsFile = function(fileName) {
  var extension, firstChar;
  extension = fileName.split('.')[1];
  firstChar = fileName[0];
  return firstChar !== '.' && extension === 'js';
};

getTrackers = function() {
  var currentPath, i, len, modulePath, modulesPath, name, tracker, trackerFile, trackerFiles, trackers;
  currentPath = path.dirname(fs.realpathSync(__filename));
  modulesPath = path.join(currentPath, '..', 'trackers');
  trackers = [];
  trackerFiles = fs.readdirSync(modulesPath);
  for (i = 0, len = trackerFiles.length; i < len; i++) {
    trackerFile = trackerFiles[i];
    if (isJsFile(trackerFile)) {
      name = trackerFile.split('.')[0];
      modulePath = path.join(modulesPath, name);
      tracker = require(modulePath);
      tracker.slug = slugify(tracker.name);
      tracker.path = "basic-trackers/" + tracker.slug;
      trackers.push(tracker);
    }
  }
  trackers.sort(function(a, b) {
    var nameA, nameB;
    nameA = a.name.toLowerCase();
    nameB = b.name.toLowerCase();
    if (nameA < nameB) {
      return -1;
    } else if (nameA > nameB) {
      return 1;
    } else {
      return 0;
    }
  });
  return trackers;
};

basicTrackers = getTrackers();

cloneTrackers = function() {
  var trackers;
  trackers = _.map(basicTrackers, _.clone);
  return trackers;
};

module.exports = cloneTrackers;
